### ISSUE TITLE
docker启nsq，访问管理端报错。 docker启nsq，按官方demo进行生产测试（注释消费），管理端无数据

### ISSUE THREAD

**Issue by dreamfit** [easy-swoole/nsq#3]
1.访问管理端的node菜单（IP:4171/counter）报错，UPSTREAM_ERROR: Failed to query any nsqd: parse http://{docker:4151/stats?format=json&include_clients=false: invalid character "{" in host name

2.参照官方文档编写简单代码，然后php easyswoole start。再访问管理端无数据。。https://www.easyswoole.com/Cn/Components/nsq.html。

**Comment by dreamfit** [comment]
> 1.访问管理端的node菜单（IP:4171/counter）报错，UPSTREAM_ERROR: Failed to query any nsqd: parse http://{docker:4151/stats?format=json&include_clients=false: invalid character "{" in host name
> 
> 2.参照官方文档编写简单代码，然后php easyswoole start。再访问管理端无数据。。[https://www.easyswoole.com/Cn/Components/nsq.html。](https://www.easyswoole.com/Cn/Components/nsq.html%E3%80%82)


1.问题已解决，docker yaml文件已修改正确

**Comment by dreamfit** [comment]
> > 1.访问管理端的node菜单（IP:4171/counter）报错，UPSTREAM_ERROR: Failed to query any nsqd: parse http://{docker:4151/stats?format=json&include_clients=false: invalid character "{" in host name
> > 2.参照官方文档编写简单代码，然后php easyswoole start。再访问管理端无数据。。[https://www.easyswoole.com/Cn/Components/nsq.html。](https://www.easyswoole.com/Cn/Components/nsq.html%E3%80%82)
> 
> 1.问题已解决，docker yaml文件已修改正确

2.还未解决。请看下怎么办

**Comment by kiss291323003** [comment]
composer up
解决
